PROJECT_BRIEF="Project Yukari 5.0, entry into AVC 2076"
ATTACH+=Yukari.fzz
ATTACH+=interface/sensor/MPU9250registers.ods
ATTACH+=Robodometer.ino
ATTACH+=eagle/*
ATTACH+=datasheet/DownloadDatasheet.sh

include ../hardware/piInterface/Makefile
include ../log/Makefile
include ../system/Makefile

