PROJECT_BRIEF="Project Yukari 5.0, entry into AVC 2017"

include ../robodometer/Makefile
include ../hardware/piInterface/Makefile
include ../log/Makefile
include ../attach/Makefile
include ../system/Makefile

