PROJECT_BRIEF="Project Yukari 5.0, entry into AVC 2076"
ATTACH+=../Yukari.fzz
ATTACH+=../Robodometer.ino
ATTACH+=$(wildcard ../eagle/*)
ATTACH+=../datasheet/DownloadDatasheet.sh

include ../hardware/piInterface/Makefile
include ../log/Makefile
include ../attach/Makefile
include ../system/Makefile

