LIBMAKE+=../hardware/piInterface/Makefile
CPPSRC+=../hardware/piInterface/HardwarePi.cpp

EXTRAINCDIRS +=../hardware/piInterface/

include ../hardware/sensor/Makefile
include ../interface/Makefile
include ../bits/Makefile


